/* Generate color-only, low-specificity overrides without editing shared BODY sheets. */
const fs = require('fs');
const {convertColors} = require('./migrate_workspace_colors');
function splitTopLevel(source, separator) {
  const parts = [];
  let start = 0, depth = 0, quote = '';
  for (let i = 0; i < source.length; i++) {
    const char = source[i];
    if (quote) {
      if (char === quote && source[i - 1] !== '\\') quote = '';
    } else if (char === '"' || char === "'") quote = char;
    else if (char === '(' || char === '[') depth++;
    else if (char === ')' || char === ']') depth--;
    else if (char === separator && depth === 0) {
      parts.push(source.slice(start, i)); start = i + 1;
    }
  }
  parts.push(source.slice(start));
  return parts;
}
function declarations(source) {
  return splitTopLevel(source, ';').flatMap(declaration => {
    const colon = declaration.indexOf(':');
    if (colon < 0) return [];
    let property = declaration.slice(0, colon).trim();
    let value = declaration.slice(colon + 1).trim();
    if (/^border(?:-(?:left|right|top|bottom))?$/.test(property)) {
      const color = value.match(/(?:var\([^)]*\)|#[\da-f]+|rgba?\([^)]*\)|\bwhite\b|\bblack\b)(?:\s*!important)?$/i);
      if (!color) return [];
      property += '-color'; value = color[0];
    }
    if (!/^(?:color|background(?:-color|-image)?|border(?:-.*)?-color|box-shadow|text-shadow|outline-color|fill|stroke)$/.test(property)) return [];
    return [`${property}:${value}`];
  }).join(';');
}
function rules(source) {
  let result = '', offset = 0;
  while (offset < source.length) {
    const open = source.indexOf('{', offset);
    if (open < 0) break;
    const selector = source.slice(offset, open).trim();
    let close = open + 1, depth = 1, quote = '';
    for (; close < source.length && depth; close++) {
      const char = source[close];
      if (quote) {
        if (char === quote && source[close - 1] !== '\\') quote = '';
      } else if (char === '"' || char === "'") quote = char;
      else if (char === '{') depth++;
      else if (char === '}') depth--;
    }
    if (depth) throw new Error('Unbalanced CSS source');
    const content = source.slice(open + 1, close - 1);
    if (/^@(?:media|supports)\b/.test(selector)) {
      const children = rules(content);
      if (children) result += `${selector}{\n${children}}\n`;
    } else if (!selector.startsWith('@')) {
      const colors = declarations(content);
      const selectors = splitTopLevel(selector, ',').map(part => part.trim()).filter(part => part &&
        !/(?:^|[\s>+~])(?:html|body)(?:$|[\s.:#>+~])/.test(part) && !part.includes(':root'));
      if (colors && selectors.length) result += selectors.map(part => `:where(.product-ui) ${part}`).join(',') + `{${colors}}\n`;
    }
    offset = close;
  }
  return result;
}
const sources = ['exam', 'live', 'redesign'].map(name => {
  const source = fs.readFileSync(`static/css/${name}.css`, 'utf8').replace(/\/\*[\s\S]*?\*\//g, '');
  return `/* ${name}: colors only */\n` + rules(convertColors(source));
});
fs.writeFileSync('static/css/workspace-legacy-palette.css',
  '/* Generated by tools/build_legacy_palette.js. Learning UI only; no layout or BODY changes. */\n' + sources.join('\n'));
